name: Aleph.js Compiler Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Testing
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Cargo test
        run: cargo test --all

      - name: Deno test
        run: deno test -A
